config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'datenschutz', to: 'home#datenschutz'
  get 'impressum', to: 'home#impressum'

  post 'login', to: 'account#login'
  post 'register', to: 'account#register'
  post 'logout', to: 'account#logout'

  get 'kurs', to: 'kurs#index'
  get 'kurs/fortschritt'
  post 'kurs/reset', to: 'kurs#reset'
  get 'kurs/:kurs', to: 'kurs#kurs'
  get 'kurs/:kurs/:kapitel', to: 'kurs#kapitel'
  get 'kurs/:kurs/:kapitel/edit', to: 'kurs#kapitel'
  get 'kurs/:kurs/:kapitel/quiz', to: 'kurs#quiz'
  post 'kurs/:kurs/:kapitel/quiz', to: 'kurs#answer'

  scope 'forum' do
    resources :posts, except: %i[index edit], shallow: true do
      post 'vote', on: :member
      resources :comments, except: %i[index edit show new], shallow: true do
        post 'vote', on: :member
        resources :replies, except: %i[index edit show new], shallow: true do
          post 'vote', on: :member
        end
      end
    end
  end
  get 'forum', to: 'forum#index'
  post 'forum/reset', to: 'forum#reset'

  get 'profile', to: 'account#profile'
  get 'profile/:user', to: 'account#profile'
  post 'profile/edit', to: 'account#edit'
  post 'account/settings', to: 'account#settings'
  post 'account/password', to: 'account#change_password'

  # get 'show', to: 'exception#show'
  # error pages
  %w[404 422 500 503].each do |code|
    get code, :to => "exception#show", :code => code
  end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  class << self
    attr_accessor :klass
  end

  def index
    @posts = Post.includes(:author).select(*%i[id author_id title created_at votes visits]).all
  end

  def featured
    @posts = Post.includes(:author).featured.select(*%i[id author_id title created_at votes visits]).all
    render 'forum/index'
  end

  def vote_post
    vote(Post)
  end

  def vote_comment
    vote(Comment)
  end

  def vote_reply
    vote(Reply)
  end
end

app/views/forum/index.html.erb
<h1 class="display-3 margin-left-10">Forum</h1>

<!-- Card -->
<div id="entrys" class="margin-left-10 card float-left">

  <!-- Card content -->
  <div class="card-body p-0" style="">

    <!-- Card -->
    <div class="m-0 p-0">
      <div class="list-group" id="posts">

        <% @posts.each do |post| %>

          <a href="<%= post_url(post.id) %>"
             data-votes="<%= post.votes.count %>"
             data-visits="<%= post.visits %>"
             data-date="<%= post.created_at.to_i %>"
             class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-2 h5"><%= post.title %></h5>
            </div>
            <small class="d-inline pr-2"><%= post.author.display_name %></small>
            <small class="d-inline pr-2">|</small>
            <small class="d-inline pr-2"><%= post.created_at.strftime('%d.%m.%Y %H:%M') %></small>

            <div class="float-right" style="margin-top: -10px">
              <i class="d-inline fas fa-arrow-up"></i>
              <p class="d-inline"><%= post.votes.count %></p>
            </div>
          </a>

        <% end %>

      </div>
    </div>
  </div>
</div>

<!-- Card -->
<div id="menu" class="margin-right-rem card float-right">

  <!-- Card content -->
  <div class="card-body">

    <!-- Card -->
    <div class="text-center h-100 w-100">
      <div class="w-100">
        <button type="button" class="btn btn-purple btn-lg btn-block" <%= 'disabled' unless @user %>
                onclick="location.href='/forum/posts/new';">Eintrag erstellen</button>
      </div>

      <hr class="hr-dark w-100">

      <!-- Search bar -->
      <div class="md-form md-bg input-with-pre-icon">
        <i class="fas fa-search input-prefix purple-text" aria-hidden="true"></i>
        <input type="text" id="search-text" class="form-control bottom-border-purple">
        <label for="search-text" class="purple-text">Suchen... </label>
      </div>

      <hr class="hr-dark w-100">

      <div class="text-left">
        <p class="h4">Sortieren nach</p>

        <!-- Neuste -->
        <div class="custom-control custom-radio">
          <input type="radio" class="custom-control-input" id="new" name="sortRadio" value="date" checked>
          <label class="custom-control-label" for="new"><span>Neuste</span></label>
        </div>

        <!-- Beliebtheit -->
        <div class="custom-control custom-radio">
          <input type="radio" class="custom-control-input" id="popularity" name="sortRadio" value="visits">
          <label class="custom-control-label" for="popularity"><span>Beliebtheit</span></label>
        </div>

        <!-- Likes -->
        <div class="custom-control custom-radio">
          <input type="radio" class="custom-control-input" id="likes" name="sortRadio" value="votes">
          <label class="custom-control-label" for="likes"><span>Likes</span></label>
        </div>

      </div>
    </div>

  </div>
</div>

<script !src="">
  $(function () {
    $("#search-text").on("keyup", function () {
      var value = $(this).val().toLowerCase();
      $("#posts a.list-group-item").filter(function () {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
    $("input[type=radio][name=sortRadio]").change(function() {
      let value = $(this).val();
      let elements = []
      let list = $("#posts a.list-group-item")

      list.each(function(_, e) {
        elements.push([$(e).data(value), e])
      })
      elements.sort(function(a, b) { return b[0] - a[0] })
      elements.forEach(function(e) {
        document.getElementById('posts').appendChild(e[1])
      })
    });
  });
</script>

app/views/forum/new.html.erb
<h1 class="display-3 margin-left-10">Neuen Eintrag erstellen</h1>

<!-- Card -->
<div id="new-entry-div" class="margin-left-10 card float-left">

  <!-- Card content -->
  <div class="card-body">
    <form action="/forum/posts" method="post">
      <p class="h2">Titel</p>
      <!-- Material background input -->
      <div class="md-form md-bg w-100">
        <input type="text" id="new-entry-title" name="post[title]" autocomplete="off" class="form-control bottom-border-purple" required>
        <label for="new-entry-title" class="purple-text">Titel</label>
      </div>

      <p class="h2">Inhalt</p>
      <div id="entry-content-div" class="md-form md-bg w-100" style="height: 200px;">
        <textarea id="entry-content" name="post[content]" required
                  class="h-100 md-textarea form-control bottom-border-purple" style="overflow-y: auto" rows="3"></textarea>
        <label for="entry-content"></label>
      </div>

      <div class="margin-bottom-10 margin-right-10 align-bottom-right">
        <button class="btn btn-purple" type="submit"><i class="fas fa-plus-circle" style="margin-right: 5px"></i>Erstellen</button>
      </div>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    </form>

  </div>
</div>

<!-- Card -->
<div id="new-entry-menu" class="card float-right margin-right-rem">

  <!-- Card content -->
  <div class="card-body">

    <!-- Card -->
    <div class="h-100 w-100">
      <p class="h2">Tipps</p>

      <div style="margin-top: 30px">
        <div class="d-inline-block">
          <span class="numberCircle clrPurple float-left"><span>1</span></span>
          <p class="ml-5">Der Titel sollte alle wichtigen Informationen kurz und genau beschreiben, damit Leute ihn besser finden können
          </p>
        </div>

        <div class="d-inline-block mt-3">
          <span class="float-left numberCircle clrPurple"><span>2</span></span>
          <p class="ml-5">
            Beim Inhalt soll das Problem genau erklärt werden.
            Zusätzlich sollte man schon vorab erwähnen, was man schon probiert hat
          </p>
        </div>

        <div class="d-inline-block mt-3">
          <span class="float-left numberCircle clrPurple"><span>3</span></span>
          <p class="ml-5">
            Wenn dein Post zu wenig Aufmerksamkeit bekommt, versuche ihn auf Social Media zu teilen! Damit können wesentlich mehr
            Leute deine Frage sehen und es ist auch für diese Seite ein kleiner Support.
          </p>
        </div>


      </div>

    </div>

  </div>
</div>

app/views/forum/post.html.erb
<h1 class="display-3 margin-left-10 title"><%= @post.title %></h1>

<div id="post-main" class="float-left">

  <!-- Card -->
  <div class="margin-left-10 card float-left" style="margin-top: 2px; margin-right: 1px">
    <!-- Card content -->
    <div class="card-body">
      <p><%= @post.content %></p>
    </div>

    <div class="card-footer post-footer d-flex justify-content-between mt-4" style="padding-left: 10px; padding-right: 10px">
      <p class="m-0"><%= @post.author.display_name %></p>
      <p class="m-0"><%= @post.created_at.strftime('%d.%m.%Y %H:%M') %></p>
      <span class="m-0 post-upvotes">
        <% if @user %>
          <%= button_to vote_post_path(@post.id), method: :post, remote: false, class: 'h-btn',
              params: { vote: !@post.user_voted?(@user.id) } do %>
            <i class="d-inline fas fa-arrow-up margin-right-10"></i>
          <% end %>
          <%= @post.votes.count %>

          <% if @post.author_id == @user.id || @user.moderator? %>
            <%= button_to post_path(@post.id), method: :delete, remote: false, class: 'h-btn' do %>
              <i class="d-inline fas fa-times ml-4 margin-right-10" data-toggle="tooltip" data-placement="top"
                 title="Post löschen"></i>
            <% end %>
          <% end %>
        <% else %>
          <i class="d-inline fas fa-arrow-up margin-right-10"></i>
          <%= @post.votes.count %>
        <% end %>

      </span>
    </div>
  </div>


  <p class="h1 margin-left-10">Kommentare</p>
  <% @post.comments.each do |comment| %>
    <!-- Card -->
    <div class="margin-left-10 card float-left" style="margin-right: 2px">
      <!-- Card content -->
      <div class="card-body">
        <p><%= comment.content %></p>
      </div>

      <div class="d-flex justify-content-between post-footer">
        <p class="m-0" style="padding-left: 20px"><%= comment.author.display_name %></p>
        <p class="m-0"><%= comment.created_at.strftime('%d.%m.%Y %H:%M') %></p>
        <span class="m-0 post-upvotes" style="padding-right: 20px">
          <% if @user %>
            <%= button_to vote_comment_path(comment.id), method: :post, remote: false, class: 'h-btn',
                params: { vote: !comment.user_voted?(@user.id) } do %>
              <i class="d-inline fas fa-arrow-up margin-right-10"></i>
            <% end %>
            <%= comment.votes.count %>

            <% if comment.author_id == @user.id || @user.moderator? %>
              <%= button_to comment_path(comment.id), method: :delete, remote: false, class: 'h-btn' do %>
                <i class="d-inline fas fa-times ml-4 margin-right-10" data-toggle="tooltip" data-placement="top"
                   title="Kommentar löschen"></i>
              <% end %>
            <% end %>
          <% else %>
            <i class="d-inline fas fa-arrow-up margin-right-10"></i>
            <%= comment.votes.count %>
          <% end %>

        </span>
      </div>

      <div class="card-footer m-0">
        <% comment.replies.each do |reply| %>

          <p class="m-0"><%= reply.content %></p>
          <div class="d-flex justify-content-between post-footer">
            <p class="m-0"><%= reply.author.display_name %></p>
            <p class="m-0" style="margin-left: -20px !important;"><%= reply.created_at.strftime('%d.%m.%Y %H:%M') %></p>
            <span class="m-0 post-upvotes">
              <% if @user %>
                <%= button_to vote_reply_path(reply.id), method: :post, remote: false, class: 'h-btn',
                    params: { vote: !reply.user_voted?(@user.id) } do %>
                  <i class="d-inline fas fa-arrow-up margin-right-10"></i>
                <% end %>
                <%= reply.votes.count %>
                <% if reply.author_id == @user.id || @user.moderator? %>
                  <%= button_to reply_path(reply.id), method: :delete, remote: false, class: 'h-btn' do %>
                    <i class="d-inline fas fa-times ml-4 margin-right-10" data-toggle="tooltip" data-placement="top"
                       title="Antwort löschen"></i>
                  <% end %>
                <% end %>
              <% else %>
                <i class="d-inline fas fa-arrow-up margin-right-10"></i>
                <%= reply.votes.count %>
              <% end %>

            </span>
          </div>

          <hr class="hr-dark">
        <% end %>

        <form action="<%= comment_replies_path(comment.id) %>" method="post" id="commentAddForm">
          <div class="md-form input-with-post-icon grey lighten-3 m-0 d-flex" style="border-radius: 10px">
            <div class="margin-left-10 w-100">
              <input required autocomplete="off" placeholder="Antwort hinzufügen" type="text" id="commentAdd" name="reply[content]" class="form-control mb-0" style="line-height: 0">
            </div>

            <button type="submit" id="commentAddBtn" class="margin-right-10"
                    style="border: none !important" <%= 'disabled' unless @user %>>
              <i class="fas fa-angle-double-right" style="<%= 'color: #6c757d !important' unless @user %>" aria-hidden="true"></i></button>
          </div>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        </form>

      </div>
    </div>
  <% end %>

  <div class="margin-left-10 card float-left" style="width: 98.75%; margin-right: 2px">

    <!-- Card content -->
    <div class="card-body">

      <form action="<%= post_comments_path(@post.id) %>" method="post" id="commentNewForm">

        <p class="h2">Kommentar hinzufügen</p>
        <div id="newComment" class="md-form md-bg">
          <textarea id="entry-content" name="comment[content]" style="overflow-y: auto" class="h-100 md-textarea form-control bottom-border-purple" rows="3" required></textarea>
          <label for="entry-content"></label>
        </div>

        <div class="margin-bottom-10 margin-right-10 align-bottom-right">
          <button type="submit" class="btn btn-purple" <%= 'disabled' unless @user %>>
            <i class="fas fa-plus-circle" style="margin-right: 5px"></i>Erstellen
          </button>
        </div>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      </form>
    </div>

  </div>
</div>

<!-- Card -->
<div id="post-side" class="margin-right-rem card float-right">

  <!-- Card content -->
  <div class="card-body p-0">

    <h1 class="margin-left-10 margin-top-10">Andere Posts</h1>
    <hr class="hr-dark w-100">
    <p class="h4 margin-left-10">Featured Posts</p>
    <div class="list-group">
      <% Post.featured.last(3).each do |post| %>
        <a href="<%= post_path(post.id) %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="float-left h5 mb-0"><%= post.title %></h5>
            <p class="my-auto align-bottom-right margin-right-10"><%= time_ago_in_words(post.created_at) %> ago</p>
          </div>
        </a>
      <% end %>
    </div>

    <hr class="hr-dark w-100">
    <p class="h4 margin-left-10 mt-3">Neuste Posts</p>

    <div class="list-group">
      <%  Post.last(3).each do |post| %>
        <a href="<%= post_path(post.id) %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="float-left h5 mb-0"><%= post.title %></h5>
            <p class="my-auto align-bottom-right margin-right-10"><%= time_ago_in_words(post.created_at) %> ago</p>
          </div>
        </a>
      <% end %>
    </div>

  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>